#!/usr/bin/env ruby

# This gems are required by the Ditto::DB::Config class
require 'yaml'
require 'sequel'

require_relative '../../db/config'
DB = Ditto::DB::Config.new.connection

# Set up your Sequel migration directory (modify as needed)
Sequel.extension :migration
Sequel::Migrator.run(DB, 'db/migrations')
